name: app

type: 'python:3.9'

dependencies:
    python3:
        pip: '21.2.4'
        pipenv: '2021.5.29'
hooks:
  build: |
    mkdir logs
    pipenv install --system --deploy
    python manage.py collectstatic
  deploy: |
    python manage.py migrate
    python manage.py generate_fake_data

relationships:
    database: 'dbpostgres:postgresql'

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:/run/app.sock bigfoot_django.wsgi:application"
        # start: "blackfire-python gunicorn -w 4 -b unix:/run/app.sock bigfoot_django.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    'logs':
        source: local
        source_path: logs
